### ISSUE TITLE
Figure out the level survey mapping

### ISSUE THREAD

**Issue by TheRealDougSchmidt** [AquaticInformatics/eHSN-field-data-plugin#13]
It's not clear to me what values can/should be brought in as level survey measurements. We'll need to figure out the precise mapping.

**Comment by TheRealDougSchmidt** [comment]
Of the 34 supplied eHSN files, 3 of them fail in the parser with some validation exceptions (which may not be correct).

```sh
~/git/eHSN-field-data-plugin/src
$ rm ../results/*.xml.*; ./integrationTest.sh
GOOD: ../data/02KF015_201181010.xml
GOOD: ../data/05BG006_20180801_v1.xml
GOOD: ../data/05FE004_20181213_FV.xml
GOOD: ../data/05GG001_20181212_FV.xml
GOOD: ../data/05HD039_20190110_FV.xml
GOOD: ../data/05JE006_20181213_FV.xml
ERROR: ../data/05JF001_20181207_FV.xml 2019-03-01 14:52:23,111 [1] ERROR EhsnPlugin - File can be parsed but an error occurred: Not enough level check rows to determine the elevation for WWG #2.
ERROR: ../data/05JF001_20190110_FV.xml 2019-03-01 14:52:24,495 [1] ERROR EhsnPlugin - File can be parsed but an error occurred: Not enough level check rows to determine the elevation for WWG #2.
GOOD: ../data/05JF005_20181213_FV.xml
GOOD: ../data/05JF005_20190110_FV.xml
GOOD: ../data/05JG004_20181213_FV.xml
GOOD: ../data/05JG006_20181212_FV.xml
GOOD: ../data/05JK007_20181207_FV.xml
GOOD: ../data/05JM001_20181210_FV.xml
GOOD: ../data/05KD004_20181211_FV.xml
ERROR: ../data/05LC001_20181210_FV.xml 2019-03-01 14:52:34,133 [1] ERROR EhsnPlugin - File can be parsed but an error occurred: Not enough level check rows to determine the elevation for TBM.
GOOD: ../data/05LJ045_20181112_FV.xml
GOOD: ../data/05MA002_20181220_FV.xml
GOOD: ../data/05MA010_20181220_FV.xml
GOOD: ../data/05MD004_20181210_FV.xml
GOOD: ../data/05NA005_20181010_FV.xml
GOOD: ../data/05NB001_20181211_FV.xml
GOOD: ../data/05NC002_20181210_FV.xml
GOOD: ../data/05ND010_20181210_FV.xml
GOOD: ../data/06BA002_20190110_FV.xml
GOOD: ../data/06BB005_20181212_FV.xml
GOOD: ../data/06BD001_20181213_FV.xml
GOOD: ../data/06DA001_20181216_FV.xml
GOOD: ../data/06DA004_20181217_FV.xml
GOOD: ../data/06DA005_20181217_FV.xml
GOOD: ../data/06DC001_20181217_FV.xml
GOOD: ../data/07MC003_20181214_FV.xml
GOOD: ../data/07QC005_20181215_FV.xml
GOOD: ../data/07QC008_20181215_FV.xml
```

**Comment by DougSchmidt-AI** [comment]
The "**" prefix is used for some benchmarks. It appears that this prefix is used to indicate the primary benchmark for the location.

The plugin should just strip this prefix whenever it encounters it, so that an XML file with "**S16-096" is treated as a benchmark name of "S16-096".

**Comment by TheRealDougSchmidt** [comment]
From the Monday Mar 11 conf call:
- Only the Level Summary rows will yield any NG Level Survey activity.
- The Level Check rows will be used to establish changes in datum, which will need to be imported via the Provisioning API, not through a field data plugin.
- There can be more than one summary row, so the current plugin parsing log will need to be changed.

**Comment by TheRealDougSchmidt** [comment]
Alright, my notes from our Mar 11 conf call don't seem to match reality.

Here is `02HE004_20190123_FV.xml`, which was pulled from the WSC 3.10 database backed up on 2019-Feb-28:

[02HE004_20190123_FV.xml.txt](https://github.com/AquaticInformatics/eHSN-field-data-plugin/files/2985418/02HE004_20190123_FV.xml.txt)

Here is the visit's level survey in the 3.10 FVT:

![LevelSurvey3 10](https://user-images.githubusercontent.com/54773/54638922-6b03f400-4a49-11e9-9a9e-268256ecb2e5.png)

And here is the eHSN Level Notes Page:
![ehsnLevelNotes](https://user-images.githubusercontent.com/54773/54639037-a999ae80-4a49-11e9-91b8-5012c1d1b4fd.png)

And the eHSN Front Page:
![ehsnFrontPage](https://user-images.githubusercontent.com/54773/54639045-b0282600-4a49-11e9-8cdb-824c9e42eb63.png)

Where does the "10:19" come from?

Right now, it is brought in by the plugin as follows:
![image](https://user-images.githubusercontent.com/54773/54639214-13b25380-4a4a-11e9-8231-b202a0a35eb5.png)

The "BM 006-023" measurement has no time (but is brought in from the Level Checks Table, it doesn't appear in the LevelSummaryTable)
The "MP ROD" measurement uses "09:21" (the LevelSummaryTable row time), not "10:09" (which I can't find anywhere in the file, and can't find any logic in the eHSN python app that recomputes "10:09" from any combination of other data.

**Comment by TheRealDougSchmidt** [comment]
Closing for now, since v18.4.24 has been deployed.
